version: "3"
services:
  db:
    image: "postgres"
    env_file: database.env
    container_name: "DB"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
